

async function main() {
    
    
}

main().then(() => {
    console.log("Test completed");
}).catch((error) => {
    console.error("Test failed:", error);
});